server.port=8082
spring.application.name=incentivos-service
spring.threads.virtual.enabled=true
service.donaciones.url=http://localhost:8080/servicioDeDonaciones
n8n.base-url=n8n.base-url=https://micamonzono.app.n8n.cloud/webhook-test
