server.port=8081
spring.application.name=notificaciones-service
spring.threads.virtual.enabled=true

twilio.account.sid=ACb251a720bef79eeffb7c3d59554ebaeb
twilio.auth.token=ff5385d5fc19288e4dc1984eecf1e92f
twilio.from.number=+13185689577
twilio.whatsapp.number=+14155238886
sendgrid.api.key=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
sendgrid.from.email=eperezarevalos@frba.utn.edu.ar

# Conexión al broker RabbitMQ (CloudAMQP)
spring.rabbitmq.addresses=amqps://hajnhykn:GVMD3WkUTJbBgE5L_-hnaZiJOIbjdm6o@jackal.rmq.cloudamqp.com/hajnhykn
# Nombre de la cola de notificaciones
notificaciones.queue.name=cola-notificaciones