server.port=8083
spring.application.name=logistica-service
donaciones.service.url=http://localhost:8080
logistica.client-secret=caabd13a4575c7495eed1481f918dd0137d945adba5929b5cbd2faedf93d8231
logistica.url-planificador=https://crumpled-swimming-grievous.ngrok-free.dev/api/webook/rutas

# Conexión al broker RabbitMQ (CloudAMQP)
spring.rabbitmq.addresses=amqps://hajnhykn:GVMD3WkUTJbBgE5L_-hnaZiJOIbjdm6o@jackal.rmq.cloudamqp.com/hajnhykn
# Nombre de la cola de notificaciones
notificaciones.queue.name=cola-notificaciones