server.port=8083
spring.application.name=logistica-service
donaciones.service.url=http://localhost:8080

# Conexión al broker RabbitMQ (CloudAMQP)
spring.rabbitmq.addresses=amqps://hajnhykn:GVMD3WkUTJbBgE5L_-hnaZiJOIbjdm6o@jackal.rmq.cloudamqp.com/hajnhykn
# Nombre de la cola de notificaciones
notificaciones.queue.name=cola-notificaciones